title: robotPID
hero_image: images/banner.png
description: Make your robot go straight with PID
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 3 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: ""
interests: "
technologies: ""
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: First code
